name: conftest

on:
  pull_request:
    paths:
      - .github/workflows/conftest.yaml
      - aqua.yaml
      - "**/*.rego"
  push:
    branches:
      - main
    paths:
      - .github/workflows/conftest.yaml
      - aqua.yaml
      - "**/*.rego"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v4.0.2
        with:
          aqua_version: v2.53.4
      - run: make test

  fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v4.0.2
        with:
          aqua_version: v2.53.4
      - run: make fmt
      - uses: int128/update-generated-files-action@v2
