name: conftest

on:
  pull_request:
    paths:
      - .github/workflows/conftest.yaml
      - "**/*.rego"
  push:
    branches:
      - main
    paths:
      - .github/workflows/conftest.yaml
      - "**/*.rego"

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v1.36.1
      - run: conftest verify -p .

  fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v1.36.1
      - run: opa fmt -d .
      - run: opa fmt -w .
      - uses: int128/update-generated-files-action@v2
